#!/bin/bash
echo "List of all people who contributed to Helium."
echo "This file was automatically generated by running"
echo "other/author-list.sh > AUTHORS"
echo ""
git log --pretty="%an <%ae>%n%cn <%ce>" | \
    sed "s/<efes@gizmo.home>/<efes@cs.uni.wroc.pl>/g" | \
    sort | uniq -c | sort -rn | sed "s/^[ 0-9]*//g"
