

zad1:
	gcc -march=nehalem -fomit-frame-pointer -Os -c set_row.c
	objdump -d set_row.o


zad2:
	gcc -march=nehalem -fomit-frame-pointer -Os -c sum_rows.c
	objdump -d sum_rows.o


zad3pure:
	gcc -march=nehalem -fomit-frame-pointer -Os -c my_index_pure.c
	objdump -d my_index_pure.o


zad3:
	gcc -march=nehalem -fomit-frame-pointer -Os -c my_index.c
	objdump -d my_index.o

zad4:
	gcc -march=nehalem -fomit-frame-pointer -Os -fdump-tree-all -c strrchr.c

zad5naive:
	gcc -march=nehalem -fomit-frame-pointer -O0 -c magic_main_naive.c
	objdump -d magic_main_naive.o


zad5opt:
	gcc -march=nehalem -fomit-frame-pointer -Os -c magic_main_opt.c
	objdump -d magic_main_opt.o


	
